### ISSUE TITLE
MAC OSx can't show data without any runtime error

### ISSUE THREAD

**Issue by lancexiang** [xufive/wxgl#1]
When i used your package wxgl to show a 3D Medical Image(DICOM FORMAT), there is no graph except the left bottom 'samll tools', but when i use the same code in windows, it show graph but not expected, the graph is a little bit strange, So whether the packages can only used in windows platform? Maybe the reason is the Mac OSx don't have a GPU for the 'VBO'?

**Comment by xufive** [comment]
请使用当前版本，参考最新文档。
Please use the current version and refer to the latest documents.
