### ISSUE TITLE
wxgl.wxplot' has no attribute 'plot'

### ISSUE THREAD

**Issue by qichikimochi** [xufive/wxgl#5]
Traceback (most recent call last):
  File "a.py", line 7, in <module>
    plt.plot(x, y)
AttributeError: module 'wxgl.wxplot' has no attribute 'plot'

`
import numpy as np
import wxgl.wxplot as plt

x = np.linspace(0, 2*np.pi, 361)
y = np.sin(x) * 3
plt.plot(x, y)
plt.show()
`

**Comment by xufive** [comment]
请使用当前版本，参考最新文档。
Please use the current version and refer to the latest documents.
