### ISSUE TITLE
找不到wxgl.glplot这个类

### ISSUE THREAD

**Issue by 88090964** [xufive/wxgl#6]
为什么最新安装版本找不到glplot这个类?

**Comment by weihaigang** [comment]
同问 全网找不到答案，文档的依赖我都安装完了，还是这个问题

**Comment by xufive** [comment]
当我提交了最新的0.9.6版本，还没来得及更新文档就感染了奥密克戎，导致后续工作没有及时跟进。由于新的版本改动较大，很多地方没有继承旧版本，给您带来了困惑和不便，深感抱歉。现在我已康复，正在恢复之前的工作，大约一周之后会更新到0.9.7版本。如果着急使用，请暂时安装0.9.3版本。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
